### PR TITLE
Add first run localhost instructions

### PR DESCRIPTION
**Pull request by briansage**
In order to help onboard newcommers, this commit updates `README.md`
with instructions for installing and configuring dependencies to run
Supergiant locally.

### CODE REVIEW

**Comment by robmurtha** [comment]
I'm starting to work with these instructions and found references to godep which was removed in the last merge.

**Comment by briansage** [comment]
Gah, I'm too slow! Good catch @robmurtha.

**Comment by FestivalBobcats** [comment]
Looks good @briansage. I do propose a change, though.

Since I was the guy who implemented SSL support, I needed to be able to use it locally. Outside of that, there's not really a purpose for SSL on `localhost`, so I think the section on generating the SSL files gets way out of our Readme scope. 

You can see [here](https://github.com/supergiant/supergiant/blob/master/pkg/core/core.go#L219-L221) how *unless* all 3 of the SSL-related settings are provided, SSL will be disabled.

We may want to make a note about how our AMI installer will generate a self-signed cert based on the EC2 instance hostname ([see here](https://github.com/supergiant/supergiant/blob/master/sgboot#L2-L6)). Other than that, though, the SSL options are available for anyone who wants to configure their CA-signed certs on their own setup in production.

**Comment by briansage** [comment]
OK @FestivalBobcats, changes incorporated.

See [the updated section on Development](https://github.com/supergiant/supergiant/blob/f98c71e119b9ed33aed1a69147690ab3c8f517f5/README.md#development) to see how it reads now.

**Comment by FestivalBobcats** [comment]
Looks good. Feel free to merge when Travis finishes running tests.

**Pull request merged**
