### PR TITLE
Master and Node volume size option.

### PR DESCRIPTION
**Pull request by gopherstein**
This change adds a simple volume size option for
master and minion nodes in the config.

```
    NodeVolumeSize      int                 `json:"node_volume_size"`
    MasterVolumeSize    int                 `json:"master_volume_size"`
```

if left blank, the size will default to 100GB

### CODE REVIEW

**Comment by FestivalBobcats** [comment]
You could remove this chunk of code:

```go
var volume int
if m.Kube.AWSConfig.NodeVolumeSize == 0 {
	volume = 100
} else {
	volume = m.Kube.AWSConfig.NodeVolumeSize
}
```

**by doing this in the model definition:**

```go
NodeVolumeSize      int                 `json:"node_volume_size" sg:"default=100"`
MasterVolumeSize    int                 `json:"master_volume_size" sg:"default=100"`
```

**Comment by gopherstein** [comment]
@FestivalBobcats Updated.

**Comment by zacbayhan** [comment]
Awesome! What is the easiest way to implement the updated pull request within the supergiant aws AMI? 
-oldbay

**Comment by gopherstein** [comment]
@zacbayhan You can run this branch directly. When @ben @FestivalBobcats is good with this he will merge it to master. If we can get a new release cut today, a new ami will get generated.

**Pull request merged**
