### PR TITLE
Update to heapster version

### PR DESCRIPTION
**Pull request by gopherstein**
This updates the default heapster install to 1.4 to fix issues with logging and api compatibility. 
FIXES# 233

### CODE REVIEW

**Comment by alterx** [comment]
lgtm

**Comment by gopherstein** [comment]
The test is failing because it is an outside pull from my fork... I will address this in a future update. But the actual tests passed

**Comment by gopherstein** [comment]
Actually... I will just fix it now....

**Comment by jordanrinke** [comment]
lgtm - late, but still proper.

**Pull request merged**
