### PR TITLE
fix website link in Readme

### PR DESCRIPTION
**Pull request by mpkh**
currently it points https://github.com/supergiant/supergiant/blob/master/supergiant.io

### CODE REVIEW

**Comment by FestivalBobcats** [comment]
Much appreciated @mpkh! I know this is only a tiny change, but would you mind signing our contributor agreement before I merge?

http://supergiant.github.io/docs/agreements/

**Comment by mpkh** [comment]
@FestivalBobcats hello... why... I mean can't you simply have some code of conduct?

**Comment by briansage** [comment]
Yeah, it sucks. It's what any company with investors has to do. When submitting changes to Kubernetes, they require the same process.

We have a [code of conduct](https://supergiant.github.io/docs/community/code-of-conduct.html) that protects people from jerks being jerks, but signing the agreement protects _all_ changes from Evil Corp coming along, saying, "that belongs to meeee." It keeps all the contents of Supergiant open-source forever, so we have to be consistent about it.

**Comment by mpkh** [comment]
@briansage @FestivalBobcats I don't feel right now like reading this for this change, I'm even not native English speaker and it's not very common what you really want even from me there... I'm ready to share my contribution even under WTFPL however feel free to close and steal this change if you need my passport data to get it there "OFFICIALLY"

**Pull request closed without merging**
