### PR TITLE
Change metric per node format

### PR DESCRIPTION
**Pull request by stgleb**
API endpoint

GET `/v1/api/kubes/{kube_name}/nodes/metrics`

Response body

```
{"master-node":{"cpu":"0.06149999999999989","memory":"0.431503826067256"},"worker-node":{"cpu":"0.0431666666666668","memory":"0.2798653943056244"}}
```

### CODE REVIEW

**Comment by egopher** [comment]
Maybe it's better to floor it it two-three digits?

**Comment by stgleb** [comment]
@egopher It is floating point number, when you display it will always have tail from 99999999999 or something else. It won't make any difference when display on the UI.

**Comment by josephkane** [comment]
its trivial for the ui to handle this, not a big deal

**Comment by egopher** [comment]
@josephkane @stgleb Better to handle this in UI trough...

**Pull request merged**
